--新增自主彩

DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 3026;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 3026);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 3026);

INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 50000);


DELETE FROM US_MENU_ITEM WHERE MENU_ID in (3026, 50000);
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID in (3026, 50000);
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE) values ('3026', '/drawManagement/officialGame/brandGameInsert','新增自主彩', 'brandGameInsert', '3012', '1', '1', '13', '4', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','新增自主彩',3026);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Brand Game Insert',3026);

Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE) values
 ('50000', 'lotto_console_web/#/views/brand_game','新增品牌彩种配置', 'Brand_Game', '2', '1', '1', '32', '2', '0',null, '0');

Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','新增品牌彩种配置',50000);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Brand Game',50000);