ALTER TABLE US_MENU_ITEM ADD (ICON VARCHAR2(128));
COMMENT ON COLUMN US_MENU_ITEM.ICON IS 'MENU ICON';

ALTER TABLE TCG_ADMIN.US_MENU_ITEM ADD ACCESS_TYPE VARCHAR2(3) DEFAULT ' ' NOT NULL;
COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."ACCESS_TYPE" IS '0:view 1:create 2:edit 3:delete 4:login 5:export 6:reject 7:approve';
