INSERT INTO TCG_ADMIN.ADMIN_MERCHANT (MERCHANT_ID,MERCHANT_CODE,MERCHANT_NAME,MERCHANT_TYPE,STATUS,UPLINE,US_MERCHANT_ID,PARENT_ID,CUSTOMER_ID,CREATE_OPERATOR)
SELECT
M.MERCHANT_ID,
M.MERCHANT_CODE,
M.MERCHANT_DESC,
DECODE(M.STATUS, 1, M.TYPE, DECODE(M.PARENT_ID, 0 ,9, M.TYPE) ) AS MERCHANT_TYPE,
M.STATUS,
DECODE(M2.MERCHANT_CODE, NULL, '0', M2.MERCHANT_CODE) AS UPLINE,
M.MERCHANT_ID AS US_MERCHANT_ID,
DECODE(M2.MERCHANT_ID, NULL, 0, M2.MERCHANT_ID) AS PARENT_ID,
M.CUSTOMER_ID,
M.CREATOR AS CREATE_OPERATOR
FROM TCG_CORE.US_MERCHANT M LEFT JOIN TCG_CORE.US_MERCHANT M2 ON M.PARENT_ID = M2.CUSTOMER_ID
WHERE M.MERCHANT_ID <> 1
ORDER BY M.MERCHANT_ID;
