UPDATE TCG_CORE.US_MERCHANT M
    SET M.TYPE = (
      CASE  WHEN (M.STATUS = 0 AND M.PARENT_ID = 0) THEN 9
            WHEN (M.STATUS = 1 AND M.TYPE = 2 ) THEN 2
            WHEN (M.STATUS = 1 AND M.TYPE = 0 ) THEN 0
            ELSE M.TYPE
      END
    );
UPDATE TCG_CORE.US_MERCHANT M SET M.TYPE = 1 WHERE M.MERCHANT_CODE = 'tcghpl';
UPDATE TCG_CORE.US_MERCHANT M SET M.TYPE = 1 WHERE M.MERCHANT_CODE = 'tcgaip';
