--------------------------------------------------------
--  已建立檔案 - 星期四-六月-01-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_MERCHANT
--------------------------------------------------------

  CREATE TABLE "TCG_ADMIN"."ADMIN_MERCHANT"
   (	"MERCHANT_ID" NUMBER(8,0),
	"US_MERCHANT_ID" NUMBER(8,0),
	"MERCHANT_CODE" NVARCHAR2(32),
	"MERCHANT_NAME" NVARCHAR2(64),
	"MERCHANT_TYPE" VARCHAR2(20 BYTE) DEFAULT 0,
	"STATUS" NUMBER(1,0),
	"PARENT_ID" NUMBER(8,0),
	"UPLINE" VARCHAR2(64 BYTE),
	"CUSTOMER_ID" NUMBER(8,0),
	"VERSION" NUMBER(8,0) DEFAULT 0,
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATE_OPERATOR" NUMBER(8,0)
   );

   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."MERCHANT_ID" IS '品牌ID';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."US_MERCHANT_ID" IS '品牌ID';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."MERCHANT_CODE" IS '品牌代碼';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."MERCHANT_NAME" IS '品牌名稱';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."MERCHANT_TYPE" IS '0:B2B(商业) 1:Inhouse(自家) 2:B2C(包网) 9:company(公司)';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."STATUS" IS '0停用,1?用,2.未審核';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."PARENT_ID" IS '父品牌ID, UPLINE';
   COMMENT ON COLUMN "TCG_ADMIN"."ADMIN_MERCHANT"."VERSION" IS '交易控制碼';
   COMMENT ON TABLE "TCG_ADMIN"."ADMIN_MERCHANT"  IS '品牌';
--------------------------------------------------------
--  DDL for Index TCG_MERCHANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."TCG_MERCHANT_PK" ON "TCG_ADMIN"."ADMIN_MERCHANT" ("MERCHANT_ID");

--------------------------------------------------------
--  DDL for Index ADMIN_MERCHANT_CODE_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."ADMIN_MERCHANT_CODE_UN" ON "TCG_ADMIN"."ADMIN_MERCHANT" ("MERCHANT_CODE");
--------------------------------------------------------
--  Constraints for Table ADMIN_MERCHANT
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("MERCHANT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("MERCHANT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("MERCHANT_CODE" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ADMIN_MERCHANT" ADD CONSTRAINT "ADMIN_MERCHANT_CODE_UN" UNIQUE ("MERCHANT_CODE");
