-- 彩票彩种组设置
DELETE FROM US_MENU_ITEM WHERE MENU_ID = 5500;
INSERT INTO US_MENU_ITEM (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, IS_BUTTON, ACCESS_TYPE)
VALUES (5500, 'lotto_console_web/#/views/game_group_parameter', '彩票彩种组设置', 'Game_Group_Parameter', 5, 1, 1, 7, 2, 0, 0);

DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 5500;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5500);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 5500);

DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 5500;
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '彩票彩种组设置', 5500);
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Game Group Parameter', 5500);

-- 彩票熱門排序
DELETE FROM US_MENU_ITEM WHERE MENU_ID = 5600;
INSERT INTO US_MENU_ITEM (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, IS_BUTTON, ACCESS_TYPE)
VALUES (5600, 'lotto_console_web/#/views/game_popularity_order', '彩票熱門排序', 'Game_Popularity_Order', 5, 1, 1, 8, 2, 0, 0);

DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 5600;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5600);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 5600);

DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 5600;
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '彩票熱門排序', 5600);
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Game Popularity Order', 5600);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 3025;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 3025;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE) values ('3025', '/drawManagement/brandGame/optimizeWinNo','奖号优化', 'optimizeWinNo', '3007', '1', '1', '30', '4', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','奖号优化',3025);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Win No Optimize',3025);
