-- 開獎查詢: 修改上層目錄
UPDATE US_MENU_ITEM SET PARENT_ID = 5 WHERE MENU_ID = 5400;

-- 開獎查詢: 修改權限
DELETE FROM US_ROLE_MENU_PERMISSION WHERE MENU_ID = 5400;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5400);