--------------------------------------------------------
--  已建立檔案 - 星期三-二月-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table US_OPERATOR_PASSWORD_HISTORY
--------------------------------------------------------

  CREATE TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" 
   (	"SEQ_ID" NUMBER(10,0), 
	"OPERATOR_NAME" VARCHAR2(16 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"CREATE_TIME" TIMESTAMP (6), 
	"VERSION" NUMBER(8,0) DEFAULT 0, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;

   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"."SEQ_ID" IS '流水號';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"."OPERATOR_NAME" IS '管理員名稱';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"."PASSWORD" IS '變更後的密碼';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"."CREATE_TIME" IS '變更密碼時間';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"."VERSION" IS '交易控制碼';
   COMMENT ON TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY"  IS '管理員修改密碼紀錄';
--------------------------------------------------------
--  DDL for Index US_OPERATOR_PASSWORD_HISTORY_1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY_1" ON "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" ("SEQ_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table US_OPERATOR_PASSWORD_HISTORY
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" ADD CONSTRAINT "US_OPERATOR_PASSWORD_HISTORY_1" PRIMARY KEY ("SEQ_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("OPERATOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("SEQ_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR_PASSWORD_HISTORY" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
