--------------------------------------------------------
--  已建立檔案 - 星期三-二月-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table US_OPERATOR
--------------------------------------------------------

  CREATE TABLE "TCG_ADMIN"."US_OPERATOR" 
   (	"OPERATOR_ID" NUMBER(10,0), 
	"OPERATOR_NAME" VARCHAR2(16 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"ACTIVE_FLAG" NUMBER(1,0),
	"NICKNAME" VARCHAR2(16 BYTE), 
	"VERSION" NUMBER(8,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ERROR_COUNT" NUMBER(2,0), 
	"ERROR_TIME" TIMESTAMP (6),
	"EMAIL" VARCHAR2(60 BYTE)
   ) ;

   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."OPERATOR_ID" IS '管理員ID';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."OPERATOR_NAME" IS '管理員名稱';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."PASSWORD" IS '密碼Hash';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."ACTIVE_FLAG" IS '啟用狀態 0:手動禁用 1:可登入 2:登入禁用 7:帳號已刪';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."NICKNAME" IS '暱稱';
   COMMENT ON COLUMN "TCG_ADMIN"."US_OPERATOR"."VERSION" IS '交易控制碼';
   COMMENT ON TABLE "TCG_ADMIN"."US_OPERATOR"  IS '營運管理人員資料表';
--------------------------------------------------------
--  DDL for Index US_OPERATOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."US_OPERATOR_PK" ON "TCG_ADMIN"."US_OPERATOR" ("OPERATOR_ID") 
  ;
--------------------------------------------------------
--  DDL for Index US_OPERATOR_OPERATOR_NAME_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."US_OPERATOR_OPERATOR_NAME_UN" ON "TCG_ADMIN"."US_OPERATOR" ("OPERATOR_NAME") 
  ;
--------------------------------------------------------
--  Constraints for Table US_OPERATOR
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" ADD CONSTRAINT "US_OPERATOR_PK" PRIMARY KEY ("OPERATOR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" ADD CONSTRAINT "US_OPERATOR_OPERATOR_NAME_UN" UNIQUE ("OPERATOR_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("ACTIVE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("OPERATOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("OPERATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_OPERATOR" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
