--------------------------------------------------------
--  已建立檔案 - 星期三-二月-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table US_MENU_ITEM
--------------------------------------------------------

  CREATE TABLE "TCG_ADMIN"."US_MENU_ITEM" 
   (	"MENU_ID" NUMBER(8,0), 
	"URL" VARCHAR2(100 BYTE), 
	"MENU_NAME" NVARCHAR2(100), 
	"DESCRIPTION" NVARCHAR2(500), 
	"PARENT_ID" NUMBER(8,0), 
	"IS_LEAF" NUMBER(1,0), 
	"IS_DISPLAY" NUMBER(1,0), 
	"DISPLAY_ORDER" NUMBER(8,0), 
	"TREE_LEVEL" NUMBER(3,0), 
	"VERSION" NUMBER(8,0) DEFAULT 0, 
	"IS_BUTTON" NUMBER(1,0) DEFAULT 0, 
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;

   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."MENU_ID" IS '選單ID';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."URL" IS '網址';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."MENU_NAME" IS '選單名稱';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."DESCRIPTION" IS '描述';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."PARENT_ID" IS '上層選單ID';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."IS_LEAF" IS '是否為根結點選單';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."IS_DISPLAY" IS '是否要顯示';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."DISPLAY_ORDER" IS '顯示順序';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."TREE_LEVEL" IS '目錄階層';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."VERSION" IS '交易控制碼';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MENU_ITEM"."IS_BUTTON" IS '是否為按鈕權限項目(0:否   1:是)';
   COMMENT ON TABLE "TCG_ADMIN"."US_MENU_ITEM"  IS '後台選單';
--------------------------------------------------------
--  DDL for Index US_MENU_ITEM_NAME_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."US_MENU_ITEM_NAME_UN" ON "TCG_ADMIN"."US_MENU_ITEM" ("MENU_NAME") 
  ;
--------------------------------------------------------
--  Constraints for Table US_MENU_ITEM
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" ADD CONSTRAINT "US_MENU_ITEM_NAME_UN" UNIQUE ("MENU_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("TREE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("DISPLAY_ORDER" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("IS_DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("IS_LEAF" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("PARENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("MENU_NAME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("IS_BUTTON" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MENU_ITEM" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
