--------------------------------------------------------
--  已建立檔案 - 星期五-三月-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table US_MERCHANT_OPERATOR
--------------------------------------------------------

  CREATE TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" 
   (	"SEQ_ID" NUMBER(10,0), 
	"MERCHANT_ID" NUMBER(8,0), 
	"OPERATOR_ID" NUMBER(10,0), 
	"VERSION" NUMBER(8,0) DEFAULT 0,
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) ;

   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."SEQ_ID" IS '';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."MERCHANT_ID" IS '品牌ID';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."OPERATOR_ID" IS '管理員ID';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."VERSION" IS '交易控制碼';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."CREATE_TIME" IS '';
   COMMENT ON COLUMN "TCG_ADMIN"."US_MERCHANT_OPERATOR"."UPDATE_TIME" IS '';
   COMMENT ON TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR"  IS '部門與管理員對應表';
--------------------------------------------------------
--  Constraints for Table US_MERCHANT_OPERATOR
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("UPDATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("OPERATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."US_MERCHANT_OPERATOR" MODIFY ("SEQ_ID" NOT NULL ENABLE);
