--官方彩种期号重建

DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 3027;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 3027);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 3027);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 3027;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 3027;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE) values ('3027', '/drawManagement/officialGame/officialDrawRebuildNumero','官方彩种期号重建', 'officialDrawRebuildNumero', '3002', '1', '1', '16', '4', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','官方彩种期号重建',3027);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Official Draw Rebuild Numero',3027);