Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (16,'B-LOTT','B-LOTT','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (17,'B-GAME','B-GAME','administrator','administrator');
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10066,'B-LOTT','B-LOTT','B-LOTT',10207,1,1,21,5,0,1,null,'1');
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10067,'B-GAME','B-GAME','B-GAME',10207,1,1,22,5,0,1,null,'1');
UPDATE TCG_ADMIN.US_MENU_ITEM SET URL = 'M-LOTT' ,MENU_NAME = 'M-LOTT' , DESCRIPTION = 'M-LOTT' WHERE MENU_ID ='10057';
UPDATE TCG_ADMIN.US_MENU_ITEM SET URL = 'M-PVP' ,MENU_NAME = 'M-PVP' , DESCRIPTION = 'M-PVP' WHERE MENU_ID ='10060';
UPDATE TCG_ADMIN.US_MENU_ITEM SET URL = 'M-RNG' ,MENU_NAME = 'M-RNG' , DESCRIPTION = 'M-RNG' WHERE MENU_ID ='10062';