UPDATE TCG_ADMIN.US_MENU_ITEM set MENU_ID = 10300 WHERE MENU_ID = 10302;
UPDATE TCG_ADMIN.US_MENU_ITEM set MENU_ID = 10400 WHERE MENU_ID = 10301;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 20200;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 20201;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 20202;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 10401;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 10402;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 10403;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400 WHERE MENU_ID = 10404;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400, DESCRIPTION = '基本设置' WHERE MENU_ID = 10405;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400, DESCRIPTION = '财务设置' WHERE MENU_ID = 10406;
UPDATE TCG_ADMIN.US_MENU_ITEM set PARENT_ID = 10400, DESCRIPTION = '产品设置' WHERE MENU_ID = 10407;
UPDATE TCG_ADMIN.US_ROLE_MENU_PERMISSION set MENU_ID = 10400 WHERE MENU_ID = 10301;
UPDATE TCG_ADMIN.US_ROLE_MENU_PERMISSION set MENU_ID = 10300 WHERE MENU_ID = 10302;
UPDATE TCG_ADMIN.US_MENU_ITEM SET PARENT_ID = 2, DISPLAY_ORDER = 107 WHERE MENU_ID = 10500;


DELETE TCG_ADMIN.US_MENU_ITEM WHERE MENU_ID = 10301;

UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='环境设置' WHERE API_ID = 10404 and LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='基本设置' WHERE API_ID = 10405 and LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='财务设置' WHERE API_ID = 10406 and LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='产品设置' WHERE API_ID = 10407 and LANG_CODE = 'zh_CN';

UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='创建品牌' WHERE API_ID = 20200 and LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='通过品牌' WHERE API_ID = 20201 and LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL='拒绝品牌' WHERE API_ID = 20202 and LANG_CODE = 'zh_CN';















