UPDATE US_MENU_ITEM_LABEL SET API_ID = 10400 WHERE API_ID = 10301 AND LANG_CODE = 'zh_CN';
UPDATE US_MENU_ITEM_LABEL SET API_ID = 10400 WHERE API_ID = 10301 AND LANG_CODE = 'en_US';
UPDATE US_MENU_ITEM_LABEL SET API_ID = 10300 WHERE API_ID = 10302 AND LANG_CODE = 'zh_CN';
UPDATE US_MENU_ITEM_LABEL SET API_ID = 10300 WHERE API_ID = 10302 AND LANG_CODE = 'en_US';

UPDATE US_MENU_ITEM_LABEL SET LABEL = '天成平台公告' WHERE API_ID = 10500 AND LANG_CODE = 'zh_CN';
UPDATE US_MENU_ITEM_LABEL SET LABEL = '商户设置' WHERE API_ID = 10400 AND LANG_CODE = 'zh_CN';
UPDATE US_MENU_ITEM_LABEL SET LABEL = 'Merchants' WHERE API_ID = 10400 AND LANG_CODE = 'en_US';
