ALTER TABLE ANNOUNCEMENT
ADD (tmpEn_Summary  NVARCHAR2(150));

UPDATE ANNOUNCEMENT SET tmpEn_Summary = EN_SUMMARY;
COMMIT;

ALTER TABLE ANNOUNCEMENT DROP COLUMN EN_SUMMARY;

ALTER TABLE ANNOUNCEMENT
RENAME COLUMN tmpEn_Summary TO EN_SUMMARY;




ALTER TABLE ANNOUNCEMENT
ADD (tmpCn_summary  NVARCHAR2(150));

UPDATE ANNOUNCEMENT SET tmpCn_summary = CN_SUMMARY;
COMMIT;

ALTER TABLE ANNOUNCEMENT DROP COLUMN CN_SUMMARY;

ALTER TABLE ANNOUNCEMENT
RENAME COLUMN tmpCn_summary TO CN_SUMMARY;



ALTER TABLE ANNOUNCEMENT
ADD (tmpMERCHANTS  NVARCHAR2(4000));

UPDATE ANNOUNCEMENT SET tmpMERCHANTS = MERCHANTS;
COMMIT;

ALTER TABLE ANNOUNCEMENT DROP COLUMN MERCHANTS;

ALTER TABLE ANNOUNCEMENT
RENAME COLUMN tmpMERCHANTS TO MERCHANTS;