Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10302,'#BehaviorLog','Behavior Log','Behavior Log',2,1,1,106,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10500,'#Announcement','后台公告','后台公告',4,1,1,25,2,0,0,null,'0');

