 CREATE TABLE "TCG_ADMIN"."ANNOUNCEMENT"
   (	"ANNOUNCEMENT_ID" NUMBER(8,0),
	"STATUS" NUMBER(1,0),
	"FREQUENCY" NUMBER(8,0) DEFAULT 0,
	"START_TIME" TIMESTAMP (6),
	"MERCHANT_TYPE" NUMBER(8,0) DEFAULT 0,
	"MERCHANTS" CLOB,
	"EN_SUMMARY" CLOB,
	"CN_SUMMARY" CLOB,
	"EN_CONTENT" CLOB,
	"CN_CONTENT" CLOB
   );


   COMMENT ON COLUMN "TCG_ADMIN"."ANNOUNCEMENT"."ANNOUNCEMENT_ID" IS 'ID';
   COMMENT ON COLUMN "TCG_ADMIN"."ANNOUNCEMENT"."START_TIME" IS 'Announcement start time';
--------------------------------------------------------
--  DDL for Index ANNOUNCEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TCG_ADMIN"."ANNOUNCEMENT_PK" ON "TCG_ADMIN"."ANNOUNCEMENT" ("ANNOUNCEMENT_ID");
--------------------------------------------------------
--  Constraints for Table ANNOUNCEMENT
--------------------------------------------------------

  ALTER TABLE "TCG_ADMIN"."ANNOUNCEMENT" MODIFY ("MERCHANT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ANNOUNCEMENT" MODIFY ("ANNOUNCEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ANNOUNCEMENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."ANNOUNCEMENT" ADD CONSTRAINT "ANNOUNCEMENT_PK" PRIMARY KEY ("ANNOUNCEMENT_ID");

