Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','超级查询',491);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Full Read Access',491);
Insert into TCG_ADMIN.US_MENU_ITEM_AUX (MENU_ID,API_TYPE,API_FAMILY) values (491,0 ,null);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE) values ( '491', '超级查询','超级查询', '超级查询', '167', '1', '0', '6', '4', '1',null, '0');
