CREATE INDEX "TCG_ADMIN"."BEHAVIOR_LOG_INDEX3" ON "TCG_ADMIN"."BEHAVIOR_LOG" ("START_PROC_DATE", "RESOURCE_TYPE", "RESOURCE_ID", "MERCHANT_CODE");
CREATE INDEX "TCG_ADMIN"."BEHAVIOR_LOG_INDEX4" ON "TCG_ADMIN"."BEHAVIOR_LOG" ("START_PROC_DATE", "RESOURCE_TYPE", "RESOURCE_ID");
CREATE INDEX "TCG_ADMIN"."BEHAVIOR_LOG_INDEX5" ON "TCG_ADMIN"."BEHAVIOR_LOG" ("START_PROC_DATE", "MERCHANT_CODE");
CREATE INDEX "TCG_ADMIN"."BEHAVIOR_LOG_INDEX6" ON "TCG_ADMIN"."BEHAVIOR_LOG" ("START_PROC_DATE", "RESOURCE_ID", "MERCHANT_CODE");
CREATE INDEX "TCG_ADMIN"."BEHAVIOR_LOG_INDEX7" ON "TCG_ADMIN"."BEHAVIOR_LOG" ("START_PROC_DATE", "RESOURCE_ID");

UPDATE TCG_ADMIN.US_MENU_ITEM SET PARENT_ID = 1 WHERE MENU_ID =10300;