Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10301,'SYSTEM VIEW','SYSTEM　VIEW','SYSTEM　VIEW',10300,1,1,107,3,0,1,null,'1');

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (12001,'wps-console-web/#/MerFunctionalMapping','Update Create of Module Mapping','Module mapping for WPS gateway',3,1,1,3,2,0,0,null,'9');

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (12002,'/MerFunctionalMapping/Update','Update Module Mapping','Update Module mapping for WPS gateway',12001,1,1,1,3,0,0,null,'9');

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (12003,'/MerFunctionalMapping/Refresh','Refresh Cache for Module Mapping','Refresh Cache for Module Mapping',12001,1,1,2,3,0,0,null,'9');