DELETE FROM US_MENU_ITEM WHERE MENU_ID = 5400;
INSERT INTO US_MENU_ITEM (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, IS_BUTTON, ACCESS_TYPE)
VALUES (5400, 'lotto_console_web/#/views/draw_history', '开奖纪录查询', 'Draw_History', 6, 1, 1, 4, 2, 0, 0);

DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 5400;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5400);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 5400);

DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 5400;
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '开奖纪录查询', 5400);
INSERT INTO US_MENU_ITEM_LABEL (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Draw History', 5400);

