ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD SUB_SYSTEM_TASK VARCHAR2(32 BYTE);
ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD STATUS VARCHAR2(1 BYTE);
ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD OPEN_TIME TIMESTAMP(6);
ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD CLOSE_TIME TIMESTAMP(6);
ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD DESCRIPTION VARCHAR2(500 BYTE);
ALTER TABLE TCG_ADMIN.WF_TRANSACTION ADD OWNER_NAME VARCHAR2(500 BYTE);