Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','在权限中初始化菜单',10107);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Initialize Menu Permission',10107);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','任务管理',10600);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Task',10600);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','历史任务管理',10700);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','TaskHistory',10700);

UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='玩家游戏统计' WHERE LANG_CODE='zh_CN' AND API_ID = 31067;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='玩家投注返点' WHERE LANG_CODE='zh_CN' AND API_ID = 31050;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='彩票投注记录' WHERE LANG_CODE='zh_CN' AND API_ID = 31002;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='彩票订单记录' WHERE LANG_CODE='zh_CN' AND API_ID = 2223;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='三方彩票记录' WHERE LANG_CODE='zh_CN' AND API_ID = 50200;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='电子游戏记录' WHERE LANG_CODE='zh_CN' AND API_ID = 31046;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='三方游戏记录' WHERE LANG_CODE='zh_CN' AND API_ID = 40020;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='三方体育订单' WHERE LANG_CODE='zh_CN' AND API_ID = 50100;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='棋牌游戏记录' WHERE LANG_CODE='zh_CN' AND API_ID = 31063;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='三方棋牌记录' WHERE LANG_CODE='zh_CN' AND API_ID = 40090;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='购买金币记录' WHERE LANG_CODE='zh_CN' AND API_ID = 40080;

UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Player Game Statistics' WHERE LANG_CODE='en_US' AND API_ID = 31067;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Player Rebates' WHERE LANG_CODE='en_US' AND API_ID = 31050;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Lotto Bet Records' WHERE LANG_CODE='en_US' AND API_ID = 31002;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Lotto Order Records' WHERE LANG_CODE='en_US' AND API_ID = 2223;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Third Party Lotto Bet Details' WHERE LANG_CODE='en_US' AND API_ID = 50200;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='RNG Game Records' WHERE LANG_CODE='en_US' AND API_ID = 31046;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Third Party Game Bets' WHERE LANG_CODE='en_US' AND API_ID = 40020;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Third Party Sports Bet Details' WHERE LANG_CODE='en_US' AND API_ID = 50100;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='PVP Game Records' WHERE LANG_CODE='en_US' AND API_ID = 31063;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Third Party PVP Records' WHERE LANG_CODE='en_US' AND API_ID = 40090;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='VC Purchase Records' WHERE LANG_CODE='en_US' AND API_ID = 40080;
