CREATE TABLE "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING"
( "SEQ_ID" NUMBER(8,0) NOT NULL ENABLE,
"OPERATOR_ID" NUMBER(8,0) NOT NULL ENABLE,
"ANNOUNCEMENT_ID" NUMBER(12,0) NOT NULL ENABLE,
"VERSION" NUMBER(8,0) DEFAULT 0 NOT NULL ENABLE,
"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
) ;

COMMENT ON COLUMN "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING"."SEQ_ID" IS 'pKey';
COMMENT ON COLUMN "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING"."OPERATOR_ID" IS 'Operator Id';
COMMENT ON COLUMN "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING"."ANNOUNCEMENT_ID" IS 'Announcement ID that is read already';
COMMENT ON COLUMN "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING"."VERSION" IS '交易控制碼';

COMMENT ON TABLE "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING" IS 'Mapping Table for Read announcement';
-- DDL for Index PS_READ_ANNOUNCEMENT_MAPPING_PK
CREATE UNIQUE INDEX "TCG_ADMIN"."READ_ANNOUNCEMENT_PK" ON "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING" ("SEQ_ID");
-- Constraints for Table PS_READ_ANNOUNCEMENT_MAPPING
ALTER TABLE "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING" ADD CONSTRAINT "READ_ANNOUNCEMENT_PK" PRIMARY KEY ("SEQ_ID")
USING INDEX ENABLE;
ALTER TABLE "TCG_ADMIN"."READ_ANNOUNCEMENT_MAPPING" ADD CONSTRAINT "READ_ANNOUNCEMENT_UK1" UNIQUE ("OPERATOR_ID", "ANNOUNCEMENT_ID");

CREATE SEQUENCE "TCG_ADMIN"."SEQ_READ_ANNOUNCEMENT" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 1000 NOORDER CYCLE ;