ALTER TABLE TCG_ADMIN.ANNOUNCEMENT ADD ANNOUNCEMENT_TYPE VARCHAR2(20 BYTE);
COMMENT ON COLUMN "TCG_ADMIN"."ANNOUNCEMENT"."ANNOUNCEMENT_TYPE" IS '1= 紧急_Emergency, 2= 平台维护 _Maintenance, 3 = 功能变动_Update, 4 = 游戏维护_GAME_MAINTENANCE, 5 = 游戏变动_GAME_MODIFICATION,6 = 其他_OTHER';

ALTER TABLE TCG_ADMIN.ANNOUNCEMENT ADD CREATE_TIME TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TCG_ADMIN.ANNOUNCEMENT ADD UPDATE_TIME TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE TCG_ADMIN.ANNOUNCEMENT ADD  VERSION NUMBER(8,0) DEFAULT 0;

ALTER TABLE TCG_ADMIN.ANNOUNCEMENT ADD (VENDOR VARCHAR2(10) )
