delete from TCG_ADMIN.WF_TASK a where rowid<(select max(rowid) from TCG_ADMIN.WF_TASK b where a.SUB_SYSTEM_TASK = b.SUB_SYSTEM_TASK);

ALTER TABLE "TCG_ADMIN"."WF_TASK" ADD CONSTRAINT "WF_TASK_UK1" UNIQUE ("STATE_ID", "SUB_SYSTEM_TASK", "STATUS")
USING INDEX  ENABLE;