DELETE
FROM PURGE_DATA_SETTING
WHERE PURGE_SEQUENCE  = 10;

DELETE
FROM PURGE_DATA_SETTING
WHERE PURGE_SEQUENCE  = 20;

DELETE
FROM PURGE_DATA_SETTING
WHERE PURGE_SEQUENCE  = 30;

INSERT INTO PURGE_DATA_SETTING(ID,TABLE_NAME,PURGE_TYPE,PURGE_SEQUENCE,ACTIVE,RETAIN_DAYS,CONDITION) VALUES
(SEQ_PURGE_DATA_SETTING.nextval, 'BEHAVIOR_LOG', 1, 10, 1, 32,  'CREATE_TIME < :retain_day');

INSERT INTO PURGE_DATA_SETTING(ID,TABLE_NAME,PURGE_TYPE,PURGE_SEQUENCE,ACTIVE,RETAIN_DAYS,CONDITION) VALUES
(SEQ_PURGE_DATA_SETTING.nextval, 'WF_TRANSACTION', 1, 20, 1, 62,  'CREATE_TIME < :retain_day');

INSERT INTO PURGE_DATA_SETTING(ID,TABLE_NAME,PURGE_TYPE,PURGE_SEQUENCE,ACTIVE,RETAIN_DAYS,CONDITION) VALUES
(SEQ_PURGE_DATA_SETTING.nextval, 'WF_TASK', 1, 30, 1, 62,  'CREATE_TIME < :retain_day');
