//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.09 at 04:06:30 PM CST 
//


package com.tcg.admin.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequsetIntervalType", propOrder = {
        "ignoreList",
})
@XmlRootElement(name = "RequestInterval")
public class RequestIntervalType {

    @XmlElement(name = "IgnoreList", required = true)
    protected IgnoreListType ignoreList;
//    @XmlElement(name = "BlackList", required = true)
//    protected BlackListType blackList;

    /**
     * Gets the value of the ignoreList property.
     * 
     * @return
     *     possible object is
     *     {@link IgnoreListType }
     *     
     */
    public IgnoreListType getIgnoreList() {
        return ignoreList;
    }

    /**
     * Sets the value of the ignoreList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IgnoreListType }
     *     
     */
    public void setIgnoreList(IgnoreListType value) {
        this.ignoreList = value;
    }

//    /**
//     * Gets the value of the blackList property.
//     *
//     * @return
//     *     possible object is
//     *     {@link BlackListType }
//     *
//     */
//    public BlackListType getBlackList() {
//        return blackList;
//    }
//
//    /**
//     * Sets the value of the blackList property.
//     *
//     * @param value
//     *     allowed object is
//     *     {@link BlackListType }
//     *
//     */
//    public void setBlackList(BlackListType value) {
//        this.blackList = value;
//    }

}
