package com.tcg.admin.common.constants;


public interface IErrorCode {

    String ERROR_MESSAGE_KEY = "message";
    String ERROR_CODE_KEY = "errorCode";

    String UNKNOWN_ERROR = "UNKNOWN_ERROR";

    String DATABASE_EXCEPTION = "YX-DATABASE-RUNTIME_EXCEPTION";
    String UNKNOWN_EXCEPTION = "YX-COMMON-UNKNOWN_EXCEPTION";
    String JNDI_NAMING_EXCEPTION = "YX-JNDI-NAMING_EXCEPTION";
    String MESSAGE_QUEUE_CONNECTION_EXCEPTION = "MESSAGE_QUEUE_CONNECTION_EXCEPTION";
    String MESSAGE_CREATE_SUBSCRIBER_EXCEPTION = "MESSAGE_CREATE_SUBSCRIBER_EXCEPTION";
    String MESSAGE_CREATE_CONSUMER_EXCEPTION = "MESSAGE_CREATE_CONSUMER_EXCEPTION";
    String MESSAGE_CONSUME_EXCEPTION = "MESSAGE_CONSUME_EXCEPTION";
    String MESSAGE_SEND_EXCEPTION = "MESSAGE_SEND_EXCEPTION";
    String MESSAGE_PUBLISH_EXCEPTION = "MESSAGE_PUBLISH_EXCEPTION";
    String MESSAGE_LISTENER_EXCEPTION = "MESSAGE_LISTENER_EXCEPTION";
    String COMMUNICATION_RUNTIME_EXCEPTION = "COMMUNICATION_RUNTIME_EXCEPTION";
    String CREATE_WS_SERVICE_FAIL = "CREATE_WS_SERVICE_FAIL";

    String PARAMETER_IS_REQUIRED = "PARAMETER_IS_REQUIRED";
    String PARAMETER_NULL_EXCEPTION = "PARAMETER_NULL_EXCEPTION";

    String CAN_NOT_BE_NEGATIVE = "CAN_NOT_BE_NEGATIVE";
    String OVER_MAX_LIMIT = "OVER_MAX_LIMIT";

    String TOO_MANY_REQUEST = "TOO_MANY_REQUEST";

    String AUTH_FAIL_EXCEPTION = "AUTH_FAIL_EXCEPTION";

    String SQL_EXECUTION_FAIL = "SQL_EXECUTION_FAIL";
    
}
