UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='1' WHERE MENU_ID = '11002';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11003';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='1' WHERE MENU_ID = '11004';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11005';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '10414';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '10411';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '3' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '10412';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='0' WHERE MENU_ID = '11001';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='0' WHERE MENU_ID = '11005';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='1' WHERE MENU_ID = '11012';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11013';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '3' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11016';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='1' WHERE MENU_ID = '11022';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11023';
UPDATE TCG_ADMIN.US_MENU_ITEM SET DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '11032';

UPDATE TCG_ADMIN.US_MENU_ITEM SET URL='/merchant', DISPLAY_ORDER = '1' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='1' WHERE MENU_ID = '10401';
UPDATE TCG_ADMIN.US_MENU_ITEM SET URL='/merchant', DISPLAY_ORDER = '3' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='2' WHERE MENU_ID = '10403';
UPDATE TCG_ADMIN.US_MENU_ITEM SET MENU_NAME='品牌審核/拒绝', DESCRIPTION='品牌審核/拒绝', URL='/merchant/merchantId', DISPLAY_ORDER = '2' ,TREE_LEVEL = '3', IS_BUTTON = '1',  ACCESS_TYPE ='7' WHERE MENU_ID = '10402';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='品牌審核/拒绝' WHERE API_ID = 10402 AND LANG_CODE = 'zh_CN';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL ='Approve/Reject' WHERE API_ID = 10402 AND LANG_CODE = 'en_US';

DELETE FROM TCG_ADMIN.US_MENU_ITEM WHERE MENU_ID = 10408;