Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10502,'wps-console-web/#/MarketDashboard','市场分析图表','市场分析图表',6,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10501,'wps-console-web/#/PNLDashBoard','平台损益图表','平台损益图表',6,1,1,31,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10503,'wps-console-web/#/OnlinePlayer','在线人数','在线人数',6,1,1,33,2,0,0,null,'0');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','在线人数',10503);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','平台损益图表',10501);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','市场分析图表',10502);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','P&L KPI Diagram',10501);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Analysis Diagram',10502);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Online Player Count',10503);

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11002,'/wps-console-service/resources/domain','商户线路新增','商户线路新增',3568,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11003,'/wps-console-service/resources/domain','商户线路修改','商户线路修改',3568,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11004,'/wps-console-service/resources/domain/status','修改狀態','修改狀態',3568,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11005,'/wps-console-service/resources/domain/lines','线路分配','线路分配',3568,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10414,'/wps-console-service/resources/merchant/updateStatus','啟用/禁用','啟用/禁用',10400,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10411,'/wps-console-service/resources/merchant_info','修改基本讯息','修改基本讯息',10405,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (10412,'/wps-console-service/resources/merchant/saveEnvSettings','修改环境设置','修改环境设置',10404,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11001,'/wps-console-service/resources/verification','手机验证码搜索','手机验证码搜索',2944,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11005,'/wps-console-service/resources/feedback','投诉建议查询','投诉建议查询',2865,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11012,'/wps-console-service/resources/path','资源路径新增','资源路径新增',3841,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11013,'/wps-console-service/resources/path','资源路径修改','资源路径修改',3841,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11016,'/wps-console-service/resources/setting','资源配置修改','资源配置修改',3861,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11022,'/wps-console-service/resources/version','客户端版本新增','客户端版本新增',3642,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11023,'/wps-console-service/resources/version','客户端版本修改','客户端版本修改',3642,1,1,32,2,0,0,null,'0');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE) values (11032,'/wps-console-service/resources/parameters/list','保存配置','保存配置',2981,1,1,32,2,0,0,null,'0');
