ALTER TABLE TCG_ADMIN.WF_TASK ADD SUB_SYSTEM_TASK_TEMP NUMBER;
UPDATE TCG_ADMIN.WF_TASK SET SUB_SYSTEM_TASK_TEMP = SUB_SYSTEM_TASK;
ALTER TABLE  TCG_ADMIN.WF_TASK DROP COLUMN SUB_SYSTEM_TASK;
ALTER TABLE TCG_ADMIN.WF_TASK ADD (SUB_SYSTEM_TASK varchar(32));
UPDATE TCG_ADMIN.WF_TASK SET SUB_SYSTEM_TASK = SUB_SYSTEM_TASK_TEMP;
ALTER TABLE  TCG_ADMIN.WF_TASK DROP COLUMN SUB_SYSTEM_TASK_TEMP;