UPDATE TCG_ADMIN.US_MENU_ITEM SET PARENT_ID = 7, DISPLAY_ORDER = 6, MENU_NAME = '在线人数监控', DESCRIPTION = '在线人数监控' WHERE MENU_ID = '10503';
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'Online Player Monitoring' WHERE LANG_CODE = 'en_US' and API_ID = 10503;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '在线人数监控' WHERE LANG_CODE = 'zh_CN' and API_ID = 10503;


