DELETE FROM US_MENU_ITEM WHERE MENU_ID = 5800;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,CREATE_TIME,
UPDATE_TIME,ACCESS_TYPE) values (5800,'lotto_console_web/#/views/game_mapping_setting', '彩票产品设置', 'LOTT_Game_Mapping',
3,1,1,65,2,0,0,sysdate,sysdate, 0);

-- Label
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = '5800';
INSERT INTO US_MENU_ITEM_LABEL (API_ID, LANG_CODE, LABEL) VALUES (5800, 'zh_CN', '彩票产品设置');
INSERT INTO US_MENU_ITEM_LABEL (API_ID, LANG_CODE, LABEL) VALUES (5800, 'en_US', 'LOTT Game Mapping');

-- Permission
DELETE FROM US_ROLE_MENU_PERMISSION WHERE MENU_ID = 5800;
-- super user
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID ) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5800);
-- SSE
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID )
SELECT SEQ_ROLE_MENU_PERMISSION.NEXTVAL, ROLE_ID, 5800 FROM US_ROLE
WHERE ROLE_NAME LIKE '%SSE%';
