UPDATE WF_TASK_TYPE_LABEL SET LABEL = '商户' WHERE LABEL = '商';
UPDATE WF_TASK_TYPE_LABEL SET LABEL = '存款' WHERE LABEL = '存';
UPDATE WF_TASK_TYPE_LABEL SET LABEL = '提款' WHERE LABEL = '提';
UPDATE WF_TASK_TYPE_LABEL SET LABEL = '收款' WHERE LABEL = '收';
UPDATE WF_TASK_TYPE_LABEL SET LABEL = '系统' WHERE LABEL = '系';
UPDATE WF_TASK_TYPE_LABEL SET LABEL = '转账' WHERE LABEL = '转';