/* Permissions Grouping */
ALTER TABLE TCG_ADMIN.US_MENU_ITEM ADD (MENU_CATEGORY_ID NUMBER(8,0) DEFAULT 0);
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, CREATE_TIME, UPDATE_TIME, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10111', '#PermissionGrouping', '权限群組管理', 'Permission Grouping Management', '2', '1', '1', '5', '2', '0', '0', SYSDATE, SYSDATE, '9', '0', '0');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '权限群組管理', '10111');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Permission Grouping', '10111');


INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10112', '/menuCategory/correlateMenuItem', '新增权限群组', 'add category Grouping', '10111', '1', '1', '1', '3', '0', '1', '2', '0', '0');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10113', '/menuCategory', '删除权限群组', 'delete category Grouping', '10111', '1', '1', '1', '3', '0', '1', '3', '0', '0');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10114', '/menuCategory/edit', '修改权限群组', 'edit category Grouping', '10111', '1', '1', '1', '3', '0', '1', '3', '0', '0');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10115', '/menuCategory/merchantByMenuCategoryName', '查询群组品牌', 'query the merchants which own the category', '10111', '1', '1', '1', '3', '0', '1', '0', '0', '0');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM" (MENU_ID, URL, MENU_NAME, DESCRIPTION, PARENT_ID, IS_LEAF, IS_DISPLAY, DISPLAY_ORDER, TREE_LEVEL, VERSION, IS_BUTTON, ACCESS_TYPE, MENU_TYPE, MENU_CATEGORY_ID) VALUES ('10116', '/permissions/menuByMenuCategoryName', '查询群组权限', 'query the permission ', '10111', '1', '1', '1', '3', '0', '1', '0', '0', '0');

INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '新增权限群组', '10112');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Add Permission Grouping', '10112');

INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '删除权限群组', '10113');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Delete Permission Grouping', '10113');

INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '修改权限群组', '10114');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Edit Permission Grouping', '10114');

INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '查询群组品牌', '10115');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Qeury Merchants of Permission Grouping', '10115');

INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('zh_CN', '查询群组权限', '10116');
INSERT INTO "TCG_ADMIN"."US_MENU_ITEM_LABEL" (LANG_CODE, LABEL, API_ID) VALUES ('en_US', 'Query Menu Permission of Permission Grouping', '10116');
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE, MENU_TYPE) values ( '10900', '#RolesGenerator', 'Roles Permission Analyze',  'Roles Permission Analyze', '1', '0', '1', '3', '2', '0', NULL, '9',0);
Update TCG_ADMIN.US_MENU_ITEM set MENU_NAME = 'Roles Permission Analyze', DESCRIPTION = 'Roles Permission Analyze' where MENU_ID = '10900';

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE, MENU_TYPE) values ( '10901', '/rolesGenerator/generate', 'Generate Roles Permission',  'Generate Roles Permission', '10900', '1', '1', '1', '3', '1', NULL, '0',0);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','角色权限解析','10900');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Roles Permission Analyze','10900');

Update TCG_ADMIN.US_MENU_ITEM_LABEL set LABEL='角色权限解析' where API_ID = 10900 and LANG_CODE = 'zh_CN';
Update TCG_ADMIN.US_MENU_ITEM_LABEL set LABEL='Roles Permission Analyze' where API_ID = 10900 and LANG_CODE = 'en_US';

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','生成角色权限','10901');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Generate Roles Permission','10901');


Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11041,'wps-console-web/#/BlackAndWhiteListing','Black and White Listing','Black and White Listing',7,1,1,1,2,1,0,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11042,'wps-console-web/#/BlackAndWhiteListing/BlockByCity','Block By City','Block By City',11041,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11043,'wps-console-web/#/BlackAndWhiteListing/BlockByIP','Block By IP','Block By IP',11041,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11044,'wps-console-web/#/BlackAndWhiteListing/BlackList','search blacklistSummary','search blacklistSummary',11041,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11045,'wps-console-web/#/BlackAndWhiteListing/WhiteList','White Listing','White Listing',11041,1,1,1,2,1,0,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11051,'wps-console-web/#/BlackAndWhiteListing/BlockByCity/save','save data of block by City','save data of block by City',11042,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11052,'wps-console-web/#/BlackAndWhiteListing/BlockByCity/delete','delete data of  block by City','delete data of  block by City',11042,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11053,'wps-console-web/#/BlackAndWhiteListing/BlockByIp/save','save data of block by Ip','save data of block by Ip',11043,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11054,'wps-console-web/#/BlackAndWhiteListing/BlockByIp/delete','delete data of  block by Ip','delete data of  block by Ip',11043,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11055,'wps-console-web/#/BlackAndWhiteListing/WhiteList/save','save WhiteList ','save WhiteList ',11045,1,1,1,3,1,1,null,'9',0,0);
Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (11056,'wps-console-web/#/BlackAndWhiteListing/WhiteList/delete','delete WhiteList','delete WhiteList',11045,1,1,1,3,1,1,null,'9',0,0);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','用户登录限制','11041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','IP restriction','11041');


Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','添加屏蔽城市','11051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Block By City','11051');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','删除屏蔽城市','11052');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Block By City Delete','11052');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','添加屏蔽IP','11053');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Block By IP ','11053');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','删除屏蔽IP','11054');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Block By IP Delete','11054');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','添加白名单','11055');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save White List ','11055');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','删除白名单','11056');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','White List Delete','11056');

Insert into TCG_ADMIN.US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,VERSION,IS_BUTTON,CREATE_TIME,UPDATE_TIME,ICON,ACCESS_TYPE,MENU_TYPE,MENU_CATEGORY_ID) values (10214,'/operators/baseMerchant','修改基本商户','修改基本商户',10201,0,1,15,4,0,1,sysdate,sysdate,null,'2',1,0);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','modify User  Base Merchant',10214);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','修改基本商户',10214);
