ALTER TABLE "TCG_ADMIN"."US_OPERATOR" ADD ("BASE_MERCHANT_CODE" VARCHAR2(32));

merge into us_operator target
using (SELECT MAX(ADMIN_MERCHANT.MERCHANT_CODE) as merchant_code, US_MERCHANT_OPERATOR.OPERATOR_ID
  FROM US_MERCHANT_OPERATOR, ADMIN_MERCHANT
  WHERE ADMIN_MERCHANT.MERCHANT_ID = US_MERCHANT_OPERATOR.MERCHANT_ID
  GROUP BY US_MERCHANT_OPERATOR.OPERATOR_ID HAVING COUNT(*) = 1)
source on (target.operator_id = source.operator_id)
when MATCHED then
  update set base_merchant_code = source.merchant_code;

