UPDATE TCG_ADMIN.US_MENU_ITEM set URL = 'wps-console-web/#/MerchantTaskCreate' WHERE MENU_ID = 10401;
UPDATE TCG_ADMIN.US_MENU_ITEM set URL = 'wps-console-web/#/MerchantTaskApprove' WHERE MENU_ID = 10402;

DELETE FROM TCG_ADMIN.US_MENU_ITEM  WHERE MENU_ID = 20200;
DELETE FROM TCG_ADMIN.US_MENU_ITEM  WHERE MENU_ID = 20201;
DELETE FROM TCG_ADMIN.US_MENU_ITEM  WHERE MENU_ID = 20202;
