
UPDATE TCG_ADMIN.US_ROLE_MENU_PERMISSION set MENU_ID = 10408 WHERE MENU_ID = 20202;

DELETE FROM TCG_ADMIN.US_ROLE_MENU_PERMISSION  WHERE MENU_ID = 20200;
DELETE FROM TCG_ADMIN.US_ROLE_MENU_PERMISSION  WHERE MENU_ID = 20201;