Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (15,'MERCHANT','MERCHANT','administrator','administrator');
UPDATE TCG_ADMIN.US_CATEGORY SET CATEGORY_NAME = 'M-LOTT' , DESCRIPTION = 'M-LOTT' WHERE CATEGORY_ID ='7' AND CATEGORY_NAME ='LOTT';
UPDATE TCG_ADMIN.US_CATEGORY SET CATEGORY_NAME = 'M-PVP' , DESCRIPTION = 'M-PVP' WHERE CATEGORY_ID ='10' AND CATEGORY_NAME ='PVP';
UPDATE TCG_ADMIN.US_CATEGORY SET CATEGORY_NAME = 'M-RNG' , DESCRIPTION = 'M-RNG' WHERE CATEGORY_ID ='12' AND CATEGORY_NAME ='RNG';