--------------------------------------------------------
--  DDL for Table SYSTEM_HELPER
--------------------------------------------------------

   CREATE TABLE "TCG_ADMIN"."SYSTEM_HELPER"
   (	"HELPER_MENU_ID" NUMBER(8,0),
	"EN_CONTENT" CLOB,
	"CN_CONTENT" CLOB,
	"STATUS" NUMBER(1,0),
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"CREATE_OPERATOR" NUMBER(8,0),
	"UPDATE_OPERATOR" NUMBER(8,0),
	"CREATE_OPERATOR_NAME" VARCHAR2(16 BYTE),
	"UPDATE_OPERATOR_NAME" VARCHAR2(16 BYTE),
	"VERSION" NUMBER(8,0) DEFAULT 0,
	"STATE" NUMBER(1,0)
   );

 CREATE UNIQUE INDEX "TCG_ADMIN"."SYSTEM_HELPER_PK" ON "TCG_ADMIN"."SYSTEM_HELPER" ("HELPER_MENU_ID") ;
 COMMENT ON COLUMN "TCG_ADMIN"."SYSTEM_HELPER"."HELPER_MENU_ID" IS 'MENU_ID IN US_MENU_ITEM';
 COMMENT ON COLUMN "TCG_ADMIN"."SYSTEM_HELPER"."STATUS" IS '0:INACTIVE 1:ACTIVE';
 COMMENT ON COLUMN "TCG_ADMIN"."SYSTEM_HELPER"."STATE" IS '1: APPROVED 0: PENDING TO CREATE ';
 

INSERT INTO TCG_ADMIN.SYSTEM_HELPER (HELPER_MENU_ID,EN_CONTENT,CN_CONTENT,STATUS,CREATE_TIME,UPDATE_TIME,CREATE_OPERATOR,UPDATE_OPERATOR,CREATE_OPERATOR_NAME,UPDATE_OPERATOR_NAME,VERSION,STATE)
SELECT
M.MENU_ID,
DECODE(L.LABEL, null, 'No Content',L.LABEL) AS EN_CONTENT,
DECODE(L2.LABEL, null, '暂无内容',  L2.LABEL) AS CN_CONTENT,
1, SYSDATE, SYSDATE, 1, null, 'administrator', null, 0, 1 FROM TCG_ADMIN.US_MENU_ITEM M
LEFT JOIN TCG_ADMIN.US_MENU_ITEM_LABEL L ON M.MENU_ID = L.API_ID
AND L.LANG_CODE = 'en_US'
LEFT JOIN TCG_ADMIN.US_MENU_ITEM_LABEL L2 ON M.MENU_ID = L2.API_ID
AND L2.LANG_CODE = 'zh_CN'
WHERE M.PARENT_ID != 0
AND M.MENU_ID NOT IN (SELECT H.HELPER_MENU_ID FROM TCG_ADMIN.SYSTEM_HELPER H);
