--------------------------------------------------------
--  DDL for Table SYSTEM_HELPER_TEMP
--------------------------------------------------------

CREATE TABLE "TCG_ADMIN"."SYSTEM_HELPER_TEMP"
   (	"HELPER_MENU_ID" NUMBER(8,0),
	"REQUESTER_ID" NUMBER(10,0),
	"REQUESTER" NVARCHAR2(16),
	"EN_CONTENT_TEMP" CLOB,
	"CN_CONTENT_TEMP" CLOB,
	"CREATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"TASK_ID" NUMBER(8,0),
	"REMARKS" VARCHAR2(500 BYTE),
	"STATUS" NUMBER(1,0),
	"PROCESSED_BY" VARCHAR2(16 BYTE),
	"VERSION" NUMBER(8,0) DEFAULT 0
   );

   COMMENT ON COLUMN "TCG_ADMIN"."SYSTEM_HELPER_TEMP"."STATUS" IS '1 = ACCEPTED 0 = PENDING 2 = REJECTED';
    CREATE UNIQUE INDEX "TCG_ADMIN"."SYSTEM_HELPER_TEMP_PK" ON "TCG_ADMIN"."SYSTEM_HELPER_TEMP" ("TASK_ID") ;
    ALTER TABLE "TCG_ADMIN"."SYSTEM_HELPER_TEMP" MODIFY ("HELPER_MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."SYSTEM_HELPER_TEMP" MODIFY ("TASK_ID" NOT NULL ENABLE);
  ALTER TABLE "TCG_ADMIN"."SYSTEM_HELPER_TEMP" ADD CONSTRAINT "SYSTEM_HELPER_TEMP_PK" PRIMARY KEY ("TASK_ID")