Insert into TCG_ADMIN.WF_TASK_TYPE_LABEL (TYPE_CODE,LANG_CODE,LABEL,DESCRIPTION) values ('SYS','en_US','SYS','Helper');
Insert into TCG_ADMIN.WF_TASK_TYPE_LABEL (TYPE_CODE,LANG_CODE,LABEL,DESCRIPTION) values ('SYS','zh_CN','系','Helper');
