/* UPDATE ACCESS TPYE*/
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 2 WHERE MENU_ID = 10406; --品牌環境設置
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 2 WHERE MENU_ID = 10407; --品牌環境設置
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 2 WHERE MENU_ID = 10405; --修改基本讯息
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 2 WHERE MENU_ID = 10404; --修改环境设置
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 5 WHERE MENU_ID = 10702; --TASK HISTORY EXPORT
UPDATE TCG_ADMIN.US_MENU_ITEM SET ACCESS_TYPE = 5 WHERE MENU_ID = 10603;