Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助',10800);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper',10800);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-查看',10801);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper Check',10801);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-修改',10802);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper modify',10802);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-啟用',10803);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper active',10803);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-禁用',10804);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper disable',10804);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-創建',10805);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper Create',10805);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-批准',10806);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper Approve',10806);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','系统帮助-拒絕',10807);
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','System Helper Reject',10807);

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票赋予新上级','480');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家分析批量查询','553');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理贡献批量查询','574');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理分红批量查询','1037');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','编辑配额','1038');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票数据导出','1228');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','房间类型开启','1263');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','房间类型关闭','1264');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','游戏修改语言','1265');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','厂商修改币种','2797');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','冻结下线转账','4221');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','游戏玩家分析报表验证名称','4321');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','投注记录用户名','4322');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','游戏房间用户验证','4323');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','修改代理链接','4361');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','保存团队返点','4382');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','添加返点比例','4383');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','删除返点比例','4384');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','日工资报表','4401');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','批量派发','4404');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','SYSTEM','10051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','B2B','10052');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','SUP','10053');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','CS','10054');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','FIN','10055');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','ISD','10056');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','M-LOTT','10057');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','MGMT','10058');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','OPS','10059');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','M-PVP','10060');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','RM','10061');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','M-RNG','10062');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','OTH','10063');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','HR','10064');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','MERCHANT','10065');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','B-LOTT','10066');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','B-GAME','10067');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','SYSTEM VIEW','10301');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','修改基本讯息','10411');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','修改环境设置','10412');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','啟用/禁用商户','10414');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索任务','10601');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','领取任务','10602');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出任务','10603');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索任务历史','10701');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出任务历史','10702');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','手机验证码搜索','11001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户线路新增','11002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户线路修改','11003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','修改狀態','11004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','线路分配','11005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','资源路径新增','11012');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','资源路径修改','11013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','资源配置修改','11016');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','客户端版本新增','11022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','客户端版本修改','11023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','保存配置','11032');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','批量存款查询','20039');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','批量出款查询','20040');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出出款记录','20041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出存款记录','20042');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','消领一审任务','20043');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','消领二审任务','20044');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','消领出款任务','20045');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','审核批量调整','20059');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','提款全阅读','20067');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','后台钱包转账','20151');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户帐变讯息','30001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户帐变单独余额','30002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户帐变信用额','30003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','商户帐变购买记录','30004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','游戏类型修改','30008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注全局搜索','31003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注期号搜索','31004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注用户名搜索','31005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注订单搜索','31006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注搜索','31007');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注导出','31008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家交易导出','31010');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家交易搜索','31011');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家交易用户名搜索','31012');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家交易类型搜索','31013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家交易订单搜索','31014');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注单笔导出','31015');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','市场人数分析搜索','31017');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理贡献分析导出','31021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理分析批量查询','31022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注彩种搜索','31025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','彩票投注状态搜索','31026');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','厂商列表搜索','31027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','更新厂商列表','31028');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','普通分红派发','31030');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','签约分红派发','31031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','阶梯日工资派发','31033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','亏损佣金操作','31040');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','消费佣金操作','31041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','签约日工资派发批量操作','31043');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','签约日工资派发操作','31044');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','厂商列表删除','31045');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家返点批量派发','31051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理返点批量派发','31053');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','天成游戏搜索导出','31054');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','天成游戏玩家搜索导出','31055');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','天成游戏局号导出','31056');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','玩家返点批量查询','31057');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','代理返点批量查询','31058');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','用户搜索','31064');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','游戏搜索','31065');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','订单搜索','31066');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','全局搜索','31068');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','高级搜索','31070');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','棋牌游戏详细','31071');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索商户账号','40001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','保存商户账号','40002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索三方详细','40021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','模糊搜索三方详情','40022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出三方记录','40023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索三方全局','40024');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索玩家三方详情','40025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索三方游戏ID详情','40026');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索三方Jackpot','40027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索三方真人详情','40028');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索商户钥匙','40031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','创建商户钥匙','40032');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','更新商户钥匙','40033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索密码更新失败','40041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','重试密码更新','40042');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索异常转账','40051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','操作异常转账','40052');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索厂商对照','40061');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','更新厂商对照','40062');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','删除厂商对照','40063');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索启动游戏','40071');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索关联转账','40072');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索启动历史','40073');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索单位玩家操作失败','40074');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','金币购买搜索','40081');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','金币购买玩家搜索','40082');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出购买记录','40083');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出玩家购买记录','40084');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索全局记录','40091');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索玩家投注记录','40092');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','搜索牌局记录','40093');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出全局记录','40094');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出玩家对战记录','40095');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出玩家牌局记录','40096');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','体育未结算搜索','50101');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','体育结算搜索','50102');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','导出体育记录','50103');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','盘口未结算搜索','50201');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','盘口结算搜索','50202');

Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Room Node','103');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Room Sub Node','104');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Node','105');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Node','106');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Room Parameter','107');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Internal','108');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display External','109');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Freeze Room','110');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Annoucement','112');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Annoucement','113');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Annoucement','114');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Annoucement','115');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Annoucement','116');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Room Type','137');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Room Type','138');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Room Type','139');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Parameter','145');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Collapse Parameter','146');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Expand Parameter','147');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Parameter','148');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Parameter','149');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Parameter History','150');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create AI','152');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search AI','162');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Info','163');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Advance Search Player Info','168');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Advance Search Player Info','169');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Detail','171');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Safety Box log','185');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Main Wallet Search','187');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Adjustment Increase Search','192');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Adjustment Increase Record Search','194');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Adjustment Decrease Search','196');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Adjustment Decrease Record Search','198');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Freeze Message','200');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View Player','201');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Record','203');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Operation Log','205');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Game Parameter','216');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Game Parameter','217');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Kick Player','240');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent','303');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Agent','304');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Freeze Agent','305');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activat4e Agent','306');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Agent','307');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Agent Config','311');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Agent Config','312');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Config Movement','324');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Manger','340');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View Link','341');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit AI','473');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Player Status','475');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Rebate History','476');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Assign New Upline','477');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Link','478');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Link','479');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Assign New Upline','480');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','BD Staff','490');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Withrawal Name','494');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Safey Information','495');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','KPI Report Search','497');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Profit Loss KPI','501');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Rank','520');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Rank','521');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Rank','522');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Rank','523');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Winner','525');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Winner','526');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Winner','527');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Tournament','529');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Tournament','530');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Tournament','531');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Baccarat Banker','533');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Baccarat Banker','534');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Baccarat Banker','535');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Baccarat AI ','537');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Baccarat AI','538');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Baccarat AI','539');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Tournament','541');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Not Display Tournament','542');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Email Sender','543');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Rank','550');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Analysis','552');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Analysis Batch','553');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Platform PVP KPI Search','558');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Third Party Version Update','562');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Third Party Version Update','563');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Third Party Version Update','564');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Domain','567');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Doman','568');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Domain','569');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Domain','570');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Room Analysis','572');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Contribution Batch','574');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Contribution','576');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','KPI Search','578');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Luck Search','582');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Player Luck','583');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Player Luck','584');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Rebate','696');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Rebate','697');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Merchant Parameter','701');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Collapse Merchant Parameter','702');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Expand Merchant Parameter','703');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Merchant Parameter','704');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Merchant Parameter','705');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Merchant Parameter','706');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Game Player Search','708');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Approval ','710');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Annoucement','712');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Agent Annoucement','713');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Agent Announcment','714');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Agent Annoucement','715');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Agent Annoucement','716');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Agent Annoucement','717');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Contact Number','1020');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Email','1021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update QQ No','1022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Recall Balance','1023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Rebate','1024');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Rebate','1025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Master Rebate','1027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Deposit on Behalf','1028');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Increate Quota','1031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Quota Count','1033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Report','1035');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Distribute Agent Dividend','1036');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Dividend Batch','1037');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Modify Quota Setting','1038');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Player Group','1154');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactive','1155');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit','1156');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Detail Adjustment Increase','1157');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Detail Adjustment Decrease','1158');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reset Login password','1159');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reset Payment Password','1160');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Refresh','1161');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Customer Service Record','1162');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Send Email','1163');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Nickname','1164');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Luck Control','1165');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Main Wallet Record','1166');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Game Wallet Record','1167');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Promotion Gold Record','1168');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Finacial Info','1171');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Login Info','1172');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Email Info','1173');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','AI Batch Activate','1174');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','AI Batch Inactivate','1175');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export KPI Data','1178');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Gane Room Record Export','1179');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Agent Controbution Export','1181');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','KPI A Export','1182');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','KPI B Export','1183');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Platform PVP Export','1186');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Anaylysis Export','1188');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Game','1191');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Transaction','1193');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Related Player','1195');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Batch Create Player Luck','1198');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Lock Status','1199');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search merchant Log','1203');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Finance Data','1204');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Refund','1205');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Game Server','1206');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Main Wallet','1207');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Game Wallet','1208');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add','1210');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit','1211');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete','1212');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export','1228');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Room Type','1263');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Room Type','1264');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Game Language','1265');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Lotto Commission','2000');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add PVP Commission','2001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add RNG Commission','2002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Lotto Commission','2003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update PVP Commission','2004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update RNG Commission','2005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Lotto Rate Config','2006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add PVP Rate Config','2007');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add RNG Rate Config','2008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Lotto Rate Config','2009');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update PVP Rate Config','2010');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update RNG Rate Config','2011');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','COMMISSION','2020');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','PROFITSHARE','2021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save','2022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Profitshare','2023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update ProfitShare','2024');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Room Type','2122');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Abnormal Transaction','2161');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Turnover Exclusion','2181');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Turnover Exclusion','2182');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate ','2200');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate','2201');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Order','2224');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Group Message Job','2225');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Load Email Job','2229');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','viewOrderDetails','2240');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reset Security Question','2260');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Agent Quota Search','2281');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','QuotaCountSearch','2291');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Quota Count','2292');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Quota Count','2293');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Quota Count','2294');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Quota','2300');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Game Player Analysis','2340');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Merchant Wallet','2441');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Affiliate url load data','2444');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search for Affiliate URL','2445');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Merchant Wallet','2446');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Merchant Wallet','2460');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Increase Merchant Wallet','2461');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Decrease Merchant Wallet','2462');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Merchant Wallet','2480');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Merchant Wallet','2481');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Upgrade Agent','2520');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Dividend ','2531');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Failed Password','2660');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Bet Detail Search','2727');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Merchant Config','2728');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Fail Update Password','2740');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Transactions','2741');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Vendor','2781');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Adjustment Increase','2782');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search VIS Parameters','2784');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add VIS Parameters','2785');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update VIS Parameters','2787');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete VIS Parameter','2788');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Vendor','2789');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Vendor','2791');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Vendor','2795');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Vendor','2796');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Vendor Currency','2797');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Bet Detail Export','2821');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Player Data','2840');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Total Credit Limit','2901');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search PT Games','2941');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add PT Game','2942');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete PT Game','2943');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Mobile Verification','2960');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Login','2983');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Login Detail','2984');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Encode','3003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Official Draw Result Enquiry','3004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Continuous Emply Draw Request','3005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','HLJSSC Draw Time Adjust','3006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Draw Result Enquiry','3008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Parameter Record','3013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Cancel Draw Request','3020');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Official Draw Result Detail','3021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Draw Result Detail','3022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Official Draw Result Confirm','3023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Provider Setting','3024');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Offical Lotto Confirm','3138');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Profitshare','3501');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Register','3562');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Player Register','3563');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search BBIN Games','3565');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add BBIN Game','3566');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete BBIN Game','3567');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search BBIN Merchant Accounts','3582');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add BBIN Merchant Account','3583');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update BBIN Merchant Account','3584');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete BBIN Merchant Account','3585');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','exportExcelLottOrderInfo','3601');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Hot Game','3661');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Hot Game','3681');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Hot Game','3701');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate Hot Game','3702');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Inactivate Hot Game','3703');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Hot Game','3704');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Hot Game Detail','3721');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Hot Game Detail','3722');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Exchange Hot Game Detail','3741');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Rebate','3762');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','UnlockWallet','3881');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Play Method','3902');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Lotto Play Method','3903');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','CreateMessage','3921');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Rebate Batch Date','3923');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Password Sync','4041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','freeze Account','4061');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','kickPlayer','4161');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Freeze Downline Transfer','4221');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Analysis Batch ','4321');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Username','4322');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Room Batch','4323');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add or Edit New Affiliate Url','4361');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Agent Team Rebate','4382');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add/Edit Agent Rebate Ratio','4383');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Agent Rebate Ratio','4384');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Daily Salary Report','4401');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Batch Disburse','4404');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Role','10002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Role','10003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Role','10004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Assign Permission','10005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Copy Role','10006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display User','10007');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Permission','10008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Role','10009');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','SYSTEM','10051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','B2B','10052');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','SUP','10053');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','CS','10054');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','FIN','10055');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','ISD','10056');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','M-LOTT','10057');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','MGMT','10058');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','OPS','10059');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','M-PVP','10060');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','RM','10061');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','M-RNG','10062');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','OTH','10063');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','HR','10064');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','MERCHANT','10065');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','B-LOTT','10066');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','B-GAME','10067');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Permission','10102');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Permission','10103');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Permission','10104');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Role Permission','10105');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Source','10106');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create User','10202');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Copy User','10203');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit User Status','10204');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete User','10205');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reset User Password','10206');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Assign Role','10207');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display User Role','10209');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display User','10210');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','User Change Password','10211');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','User Change Info','10212');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Display Menu','10213');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','SYSTEM VIEW','10301');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Merchant Info','10411');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Enviroment Info','10412');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Activate/Inactivate Merchant','10414');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Task ','10601');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Claim task','10602');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Task','10603');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Task History','10701');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Task History','10702');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Mobile Verification','11001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Merchant Domain','11002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Merchant Domain','11003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Domain Status','11004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Assign Domain','11005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Resource Path','11012');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Resource Path','11013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Assign Resource Patch','11016');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Client Version','11022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Client Version','11023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Merchant Setting','11032');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View All Deposit','20001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search All Deposit','20002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Process Deposit','20003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View Pending Deposit','20004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Approve Deposit','20005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reject Deposit','20006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Pending Deposit','20007');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View All Withdraw','20009');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search All Withdraw','20010');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View Pending Withdraw','20011');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Approve Withdraw','20012');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reject Withdraw','20013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','InReview Withdraw','20014');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Pending Withdraw','20015');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View In Review','20016');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Approve InReview Withdraw','20017');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reject InReview Withdraw','20018');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search InReview Withdraw','20019');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','View Pending Payment','20020');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Paid Withdraw Btn','20021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Reject Withdraw Btn','20022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Pending Payment','20023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Banks','20025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Banks','20026');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Banks','20027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Add Bank Account','20029');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Bank Account','20030');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Bank Accounts','20031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Bank Account Cash Movement','20033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Bank Account Adjustment','20034');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Withdraw Settings','20036');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Modify Withdraw Settings','20037');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Bank Account Fund Transfer','20038');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Deposit WildCard','20039');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Withdraw WildCard','20040');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export All Withdraw','20041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export','20042');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Unclaim Pending Withdraw Task','20043');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Unclaim In Review Withdraw Task','20044');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Unclaim Payment Withdraw Task','20045');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Approve Batch Player Adjustment','20059');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Full Access Withdraw','20067');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Transfer Wallet Balance','20151');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Transaction Info','30001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Product Balance','30002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Credit Limit','30003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Merchant Purcase Record','30004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Game Type','30008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Full Search','31003');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Numero Search','31004');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto User Search','31005');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Order Search','31006');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Search','31007');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Export','31008');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Transaction Export','31010');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Transaction','31011');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','SSearch Player Transaction Username','31012');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Transaction Type','31013');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Transaction Order','31014');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Lotto Detail','31015');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Market Analysis','31017');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Agent Contribution','31021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Agent Contribution Batch','31022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Bet Record','31025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Lotto Bet Record Status','31026');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Vendor List','31027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Edit Vendor List','31028');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Distribution Agent Dividend','31030');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Distribution Contract Dividend','31031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Distribution Daily Salary','31033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Profit Share Commission','31040');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Consume Comission','31041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Distribution Contract Daily Salary Batch','31043');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Contract Daily Salary','31044');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Delete Vendor List','31045');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Rebate Batch Distribution','31051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Agent Rebate Batch Distribution','31053');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','PVP Game Record Export','31054');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','PVP Game Record Player Export','31055');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','PVP Game Record Round Export','31056');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Player Rebate Search Batch','31057');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Agent Rebate Search Batch','31058');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','User Search','31064');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Game Search','31065');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Order Search','31066');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Full Search','31068');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Advance Search','31070');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','PVP Game Detail','31071');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Vendor Accounts','40001');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Vendor Account','40002');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Bet Detail List','40021');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Bet Detail List Wildcard','40022');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Bet Detail','40023');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search All Bet Details','40024');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Bet Details','40025');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Id Bet Details','40026');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Jacpot Win Bet Details','40027');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Live Game Bet Details','40028');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Merchant Key','40031');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Create Merchant Key','40032');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Update Merchant Key','40033');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Failed Update Password','40041');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Retry Update Password','40042');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Pending Transfer','40051');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Process Pending Status','40052');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Vendor Game Mapping','40061');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Save Vendor Game Mapping','40062');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Remove Vendor Game Mapping','40063');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Launch Info','40071');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Related Transfer','40072');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Game Launch History','40073');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Failed Products By Member','40074');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Purchase Record Search All','40081');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Purchase Record Search Player','40082');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export All Purchase Record','40083');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Player Purchase Record','40084');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search All Bet History','40091');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Player Bet History','40092');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Search Match Bet History','40093');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export All Bet Details','40094');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Player Bet Details','40095');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Match Bet Details','40096');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Sports Unsettled Bet Detail Search','50101');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Sports Settled Bet Detail Search','50102');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Export Sports Settled Bet Detail','50103');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Unsettled Bet Detail Search','50201');
Insert into TCG_ADMIN.US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Lotto Settled Bet Detail Search','50202');

UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '修改返点' WHERE API_ID =696;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加返点' WHERE API_ID =697;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新手机号' WHERE API_ID =1020;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新邮件' WHERE API_ID =1021;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新QQ' WHERE API_ID =1022;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '保存返点' WHERE API_ID =1027;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加胜局活动' WHERE API_ID =1210;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '修改胜局活动' WHERE API_ID =1211;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除胜局活动' WHERE API_ID =1212;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加代理佣金' WHERE API_ID =2000;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加棋牌佣金' WHERE API_ID =2001;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加电子佣金' WHERE API_ID =2002;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新棋牌佣金' WHERE API_ID =2003;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新棋牌佣金' WHERE API_ID =2004;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新电子佣金' WHERE API_ID =2005;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加彩票设置' WHERE API_ID =2006;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加棋牌设置' WHERE API_ID =2007;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加电子设置' WHERE API_ID =2008;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新彩票设置' WHERE API_ID =2009;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新棋牌设置' WHERE API_ID =2010;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新电子设置' WHERE API_ID =2011;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '佣金' WHERE API_ID =2020;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '分红' WHERE API_ID =2021;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '保存返点' WHERE API_ID =2022;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '跟新分红' WHERE API_ID =2024;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '创建批量讯息' WHERE API_ID =2225;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '载入邮件排程' WHERE API_ID =2229;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '显示订单记录' WHERE API_ID =2240;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '充值密保提问' WHERE API_ID =2260;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索代理配额' WHERE API_ID =2281;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '配额总数搜索' WHERE API_ID =2291;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加配额数量' WHERE API_ID =2292;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '修改配额数量' WHERE API_ID =2293;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除配额数量' WHERE API_ID =2294;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '载入代理链接' WHERE API_ID =2444;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索代理链接' WHERE API_ID =2445;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索失败同步' WHERE API_ID =2660;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索投注记录' WHERE API_ID =2727;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新商户配置' WHERE API_ID =2728;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索失败同步' WHERE API_ID =2740;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索交易明细' WHERE API_ID =2741;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索VIS参数' WHERE API_ID =2784;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加VIS参数' WHERE API_ID =2785;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新VIS参数' WHERE API_ID =2787;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除VIS参数' WHERE API_ID =2788;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '三方游戏导出' WHERE API_ID =2821;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索PT游戏' WHERE API_ID =2941;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加PT游戏' WHERE API_ID =2942;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除PT游戏' WHERE API_ID =2943;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '时时彩' WHERE API_ID =3012;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除平台分红' WHERE API_ID =3501;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索BBIN游戏' WHERE API_ID =3565;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加BBIN游戏' WHERE API_ID =3566;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除BBIN游戏' WHERE API_ID =3567;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索BBIN商户账号' WHERE API_ID =3582;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加BBIN商户账号' WHERE API_ID =3583;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新BBIN商户账号' WHERE API_ID =3584;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '删除BBIN商户账号' WHERE API_ID =3585;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '彩票详细导出' WHERE API_ID =3601;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '解锁钱包' WHERE API_ID =3881;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '创建消息' WHERE API_ID =3921;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '踢玩家' WHERE API_ID =4161;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'SYSTEM' WHERE API_ID =10051;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'B2B' WHERE API_ID =10052;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'SUP' WHERE API_ID =10053;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'CS' WHERE API_ID =10054;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'FIN' WHERE API_ID =10055;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'ISD' WHERE API_ID =10056;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'M-LOTT' WHERE API_ID =10057;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'MGMT' WHERE API_ID =10058;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'OPS' WHERE API_ID =10059;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'M-PVP' WHERE API_ID =10060;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'RM' WHERE API_ID =10061;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'M-RNG' WHERE API_ID =10062;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'OTH' WHERE API_ID =10063;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'HR' WHERE API_ID =10064;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'MERCHANT' WHERE API_ID =10065;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'B-LOTT' WHERE API_ID =10066;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'B-GAME' WHERE API_ID =10067;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '系统' WHERE API_ID =10301;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看全部存款' WHERE API_ID =20001;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索全部存款' WHERE API_ID =20002;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '操作存款' WHERE API_ID =20003;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看待审存款' WHERE API_ID =20004;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '通过存款' WHERE API_ID =20005;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '拒绝存款' WHERE API_ID =20006;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索待审存款' WHERE API_ID =20007;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看全部提款' WHERE API_ID =20009;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索全部提款' WHERE API_ID =20010;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看待审提款' WHERE API_ID =20011;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '通过提款' WHERE API_ID =20012;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '拒绝提款' WHERE API_ID =20013;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '二审提款' WHERE API_ID =20014;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索二审提款' WHERE API_ID =20015;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看二审提款' WHERE API_ID =20016;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '通过二审提款' WHERE API_ID =20017;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '拒绝二审提款' WHERE API_ID =20018;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索二审提款' WHERE API_ID =20019;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '查看待审支付' WHERE API_ID =20020;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '通过支付' WHERE API_ID =20021;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '拒绝支付' WHERE API_ID =20022;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索待审支付' WHERE API_ID =20023;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加银行' WHERE API_ID =20025;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新银行' WHERE API_ID =20026;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索银行' WHERE API_ID =20027;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '添加银行账号' WHERE API_ID =20029;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '更新银行账号' WHERE API_ID =20030;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索银行账号' WHERE API_ID =20031;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索银行帐变' WHERE API_ID =20033;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '创建银行调整' WHERE API_ID =20034;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '搜索提款设置' WHERE API_ID =20036;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '修改提款设置' WHERE API_ID =20037;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '创建银行转账' WHERE API_ID =20038;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '空搜索玩家转账' WHERE API_ID =20083;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = '真人' WHERE API_ID =20506;
UPDATE TCG_ADMIN.US_MENU_ITEM_LABEL SET LABEL = 'B2B转点钱包' WHERE API_ID =50250;
