UPDATE US_MENU_ITEM SET MENU_NAME = '彩种基本参数设置', DESCRIPTION = '彩种基本参数设置' WHERE MENU_ID = 5100;
UPDATE US_MENU_ITEM_LABEL SET LABEL = '彩种基本参数设置' WHERE API_ID = 5100 AND LANG_CODE = 'zh_CN';

UPDATE US_MENU_ITEM SET DISPLAY_ORDER=8  WHERE MENU_ID = 5900;
UPDATE US_MENU_ITEM SET DISPLAY_ORDER=10  WHERE MENU_ID = 6000;
UPDATE US_MENU_ITEM SET DISPLAY_ORDER=13  WHERE MENU_ID = 5500;
UPDATE US_MENU_ITEM SET DISPLAY_ORDER=15  WHERE MENU_ID = 2180;
UPDATE US_MENU_ITEM SET DISPLAY_ORDER=20  WHERE MENU_ID = 1209;
UPDATE US_MENU_ITEM SET DISPLAY_ORDER=30  WHERE MENU_ID = 5600;

--Remove Duplicate Page
DELETE FROM US_MENU_ITEM WHERE MENU_ID IN (5200,5300) ;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID IN (5200,5300) ;
-- Permission
DELETE FROM US_ROLE_MENU_PERMISSION WHERE MENU_ID IN (5200,5300) ;