--官方玩法参数设置
DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 5900;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 5900);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 5900);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 5900;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 5900;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE)
values (5900, 'lotto_console_web/#/views/play_setting','传统玩法参数设置', '传统玩法参数设置', 5, '1', '1', '6', '2', '0',null, '9');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','传统玩法参数设置',5900);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Tradition Play Parameter Setting ',5900);