--奖源接口配置
DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 3028;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 3028);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 3028);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 3028;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 3028;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE)
values (3028, '-','奖源接口配置', 'WinNo Provider Api Setting', 3011, '0', '1', '8', '3', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','奖源接口配置',3028);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','WinNo Provider Api Setting',3028);

--新增接口设置
DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 3029;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 3029);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 3029);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 3029;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 3029;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE)
values ('3029', '/platformManagement/winNoUsers/winNoUsersCreate','新增接口设置', 'winNoUsersCreate', 3028, '1', '1', '10', '4', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','新增接口设置',3029);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','WinNo Provider Api Setting Insert',3029);

--奖源接口列表
DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 3030;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 3030);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 3030);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 3030;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 3030;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE)
values ('3030', '/platformManagement/winNoUsers/winNoUsersQuery','奖源接口列表', 'winNoUsersQuery', 3028, '1', '1', '20', '4', '0',null, '0');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','奖源接口列表',3030);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','WinNo Provider Api List',3030);