--盘口玩法参数设置
DELETE FROM US_ROLE_MENU_PERMISSION WHERE (ROLE_ID = 1 OR ROLE_ID = 2) AND MENU_ID = 6000;
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 1, 6000);
INSERT INTO US_ROLE_MENU_PERMISSION (SEQ_ID, ROLE_ID, MENU_ID) VALUES (SEQ_ROLE_MENU_PERMISSION.NEXTVAL, 2, 6000);

DELETE FROM US_MENU_ITEM WHERE MENU_ID = 6000;
DELETE FROM US_MENU_ITEM_LABEL WHERE API_ID = 6000;
Insert into US_MENU_ITEM (MENU_ID,URL,MENU_NAME,DESCRIPTION,PARENT_ID,IS_LEAF,IS_DISPLAY,DISPLAY_ORDER,TREE_LEVEL,IS_BUTTON,ICON,ACCESS_TYPE)
values (6000, 'lotto_console_web/#/views/elott_setting','盘口玩法参数设置', '盘口玩法参数设置', 5, '1', '1', '7', '2', '0',null, '9');
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('zh_CN','盘口玩法参数设置',6000);
Insert into US_MENU_ITEM_LABEL (LANG_CODE,LABEL,API_ID) values ('en_US','Elott Play Parameter Setting ',6000);