/* Each time add menu_item must run this script to init data in system helper */
INSERT INTO TCG_ADMIN.SYSTEM_HELPER (HELPER_MENU_ID,EN_CONTENT,CN_CONTENT,STATUS,CREATE_TIME,UPDATE_TIME,CREATE_OPERATOR,UPDATE_OPERATOR,CREATE_OPERATOR_NAME,UPDATE_OPERATOR_NAME,VERSION,STATE)
SELECT
M.MENU_ID,
DECODE(L.LABEL, null, 'No Content',L.LABEL) AS EN_CONTENT,
DECODE(L2.LABEL, null, '暂无内容',  L2.LABEL) AS CN_CONTENT,
1, SYSDATE, SYSDATE, 1, null, 'administrator', null, 0, 1 FROM TCG_ADMIN.US_MENU_ITEM M
LEFT JOIN TCG_ADMIN.US_MENU_ITEM_LABEL L ON M.MENU_ID = L.API_ID
AND L.LANG_CODE = 'en_US'
LEFT JOIN TCG_ADMIN.US_MENU_ITEM_LABEL L2 ON M.MENU_ID = L2.API_ID
AND L2.LANG_CODE = 'zh_CN'
WHERE M.PARENT_ID != 0
AND M.MENU_ID NOT IN (SELECT H.HELPER_MENU_ID FROM TCG_ADMIN.SYSTEM_HELPER H);