Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (1,'SYSTEM','SYSTEM','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (2,'B2B','B2B','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (3,'SUP','SUP','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (4,'CS','CS','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (5,'FIN','FIN','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (6,'ISD','ISD','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (7,'LOTT','LOTT','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (8,'MGMT','MGMT','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (9,'OPS','OPS','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (10,'PVP','PVP','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (11,'RM','RM','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (12,'RNG','RNG','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (13,'OTH','OTH','administrator','administrator');
Insert into TCG_ADMIN.US_CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,CREATE_OPERATOR,UPDATE_OPERATOR) values (14,'HR','HR','administrator','administrator');

