Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (1,'SYSTEM','SYSTEM',0,1,1,'0');
Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (2,'2000cai','lotto',0,1,0,'0');
Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (3,'dele88','DELE88',0,1,0,'0');
Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (4,'500cai','B2C - 五百万彩',0,1,0,'0');
Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (5,'beiying','BeiYing',0,1,0,'0');
Insert into TCG_ADMIN.US_MERCHANT (MERCHANT_ID,MERCHANT_NAME,DESCRIPTION,PARENT_ID,ACTIVE_FLAG,DISPLAY_ORDER,TYPE) values (6,'fenghuangcai','凤凰彩票',0,1,1,'0');
Insert into TCG_ADMIN.US_MERCHANT_OPERATOR (SEQ_ID,MERCHANT_ID,OPERATOR_ID) values (1,1,1);